import { QuestionCategory } from '@/stores/gameStore';

export interface BaseQuestion {
  id: number;
  text: string;
}

// Question sets by category
export const QUESTIONS_BY_CATEGORY: Record<QuestionCategory, BaseQuestion[]> = {
  food: [
    { id: 1, text: "Do you like pineapple on pizza?" },
    { id: 2, text: "Would you eat Jollof rice every day?" },
    { id: 3, text: "Have you ever lied about liking someone's cooking?" },
    { id: 4, text: "Do you secretly hate a popular food everyone loves?" },
    { id: 5, text: "Have you ever pretended to be full to avoid eating?" },
    { id: 6, text: "Would you eat insects if they were prepared gourmet style?" },
    { id: 7, text: "Have you ever eaten something past its expiration date?" },
    { id: 8, text: "Do you judge people based on their food preferences?" },
    { id: 9, text: "Have you ever stolen food from a roommate?" },
    { id: 10, text: "Would you give up your favorite food for a year for $10,000?" },
    { id: 11, text: "Do you eat in bed regularly?" },
    { id: 12, text: "Have you ever pretended to have food allergies to avoid eating something?" },
    { id: 13, text: "Would you eat a meal prepared by someone who didn't wash their hands?" },
    { id: 14, text: "Have you ever returned food at a restaurant and pretended it was bad?" },
    { id: 15, text: "Do you lick your plate when no one is watching?" },
    { id: 16, text: "Would you eat pet food if it tasted good?" },
    { id: 17, text: "Have you ever eaten something you found on the floor?" },
    { id: 18, text: "Do you believe ketchup belongs on everything?" },
    { id: 19, text: "Have you ever eaten an entire cake by yourself?" },
    { id: 20, text: "Would you try human flesh if it was legal and ethical?" },
  ],
  sex: [
    { id: 1, text: "Have you ever lied to your partner?" },
    { id: 2, text: "Do you believe in love at first sight?" },
    { id: 3, text: "Have you ever faked being interested in someone?" },
    { id: 4, text: "Would you date someone your friend dated?" },
    { id: 5, text: "Have you ever cheated in a relationship?" },
    { id: 6, text: "Would you date someone just for their money?" },
    { id: 7, text: "Have you ever ghosted someone instead of breaking up properly?" },
    { id: 8, text: "Do you still think about your ex?" },
    { id: 9, text: "Would you date someone who's significantly older/younger than you?" },
    { id: 10, text: "Have you ever pretended to be someone else online?" },
    { id: 11, text: "Would you marry someone your family disapproves of?" },
    { id: 12, text: "Have you ever read your partner's messages without permission?" },
    { id: 13, text: "Do you believe monogamy is natural?" },
    { id: 14, text: "Have you ever stayed in a relationship just for convenience?" },
    { id: 15, text: "Would you date two people at once if you could get away with it?" },
    { id: 16, text: "Have you ever had a crush on a friend's partner?" },
    { id: 17, text: "Do you believe in soulmates?" },
    { id: 18, text: "Have you ever broken up with someone over text?" },
    { id: 19, text: "Would you take back someone who cheated on you?" },
    { id: 20, text: "Have you ever lied about your relationship status?" },
  ],
  movie: [
    { id: 1, text: "Do you pretend to have watched popular movies?" },
    { id: 2, text: "Have you ever cried during a movie?" },
    { id: 3, text: "Do you enjoy horror movies?" },
    { id: 4, text: "Have you ever walked out of a cinema?" },
    { id: 5, text: "Do you think you could act in a movie?" },
    { id: 6, text: "Have you ever fallen asleep in a movie theater?" },
    { id: 7, text: "Do you secretly enjoy movies everyone hates?" },
    { id: 8, text: "Have you ever pretended to like a movie to impress someone?" },
    { id: 9, text: "Would you watch a 5-hour movie without bathroom breaks?" },
    { id: 10, text: "Have you ever pirated a movie you could easily afford?" },
    { id: 11, text: "Do you talk during movies in the theater?" },
    { id: 12, text: "Have you ever walked into the wrong movie screening?" },
    { id: 13, text: "Would you be an extra in a movie for free?" },
    { id: 14, text: "Have you ever dated someone because they looked like a celebrity?" },
    { id: 15, text: "Do you believe movie endings should always be happy?" },
    { id: 16, text: "Have you ever spoiled a movie on purpose?" },
    { id: 17, text: "Would you watch the same movie 10 times in a row?" },
    { id: 18, text: "Have you ever pretended to understand a complicated film?" },
    { id: 19, text: "Do you judge people based on their favorite movies?" },
    { id: 20, text: "Would you sacrifice popcorn forever to save cinema?" },
  ],
  music: [
    { id: 1, text: "Do you sing in the shower?" },
    { id: 2, text: "Have you ever pretended to know a popular song?" },
    { id: 3, text: "Do you listen to music everyone makes fun of?" },
    { id: 4, text: "Have you been to a concert before?" },
    { id: 5, text: "Can you play a musical instrument?" },
    { id: 6, text: "Have you ever lip-synced while pretending to sing live?" },
    { id: 7, text: "Do you secretly enjoy songs from childhood TV shows?" },
    { id: 8, text: "Would you give up music for a year for $50,000?" },
    { id: 9, text: "Have you ever pretended to like a band to fit in?" },
    { id: 10, text: "Do you judge people's playlists?" },
    { id: 11, text: "Have you ever cried at a concert?" },
    { id: 12, text: "Would you date someone with terrible music taste?" },
    { id: 13, text: "Have you ever illegally downloaded music?" },
    { id: 14, text: "Do you believe modern music is worse than old music?" },
    { id: 15, text: "Have you ever been to a concert just to socialize?" },
    { id: 16, text: "Would you get a tattoo of your favorite artist's lyrics?" },
    { id: 17, text: "Have you ever pretended to recognize a song that was playing?" },
    { id: 18, text: "Do you secretly enjoy elevator music?" },
    { id: 19, text: "Have you ever sung karaoke while completely sober?" },
    { id: 20, text: "Would you trade your voice for perfect musical talent?" },
  ],
  sports: [
    { id: 1, text: "Do you actually enjoy watching sports?" },
    { id: 2, text: "Have you ever lied about your fitness level?" },
    { id: 3, text: "Do you pretend to understand sports rules?" },
    { id: 4, text: "Have you ever faked an injury to avoid exercise?" },
    { id: 5, text: "Would you rather watch sports than play them?" },
    { id: 6, text: "Have you ever pretended to like a sport to impress someone?" },
    { id: 7, text: "Would you take steroids if guaranteed not to get caught?" },
    { id: 8, text: "Have you ever cheered for the wrong team accidentally?" },
    { id: 9, text: "Do you believe competitive sports are bad for society?" },
    { id: 10, text: "Have you ever bet on a game you knew nothing about?" },
    { id: 11, text: "Would you let your child play dangerous sports?" },
    { id: 12, text: "Have you ever pretended to be injured during gym class?" },
    { id: 13, text: "Do you think professional athletes are overpaid?" },
    { id: 14, text: "Have you ever used sports equipment incorrectly on purpose?" },
    { id: 15, text: "Would you date someone who hates your favorite team?" },
    { id: 16, text: "Have you ever fainted during exercise?" },
    { id: 17, text: "Do you believe video games should be considered sports?" },
    { id: 18, text: "Have you ever worn sports gear without actually playing?" },
    { id: 19, text: "Would you give up watching sports forever for $100,000?" },
    { id: 20, text: "Have you ever secretly hoped your team would lose?" },
  ],
  personal: [
    { id: 1, text: "Have you ever lied about finishing homework?" },
    { id: 2, text: "Have you ever pretended to be sick to skip work?" },
    { id: 3, text: "Do you think you're a good liar?" },
    { id: 4, text: "Have you ever stolen something?" },
    { id: 5, text: "Do you keep secrets from your best friend?" },
    { id: 6, text: "Have you ever eavesdropped on a private conversation?" },
    { id: 7, text: "Would you read your friend's diary if you found it?" },
    { id: 8, text: "Have you ever pretended to be someone else on the phone?" },
    { id: 9, text: "Do you judge people based on their social media?" },
    { id: 10, text: "Have you ever taken credit for someone else's work?" },
    { id: 11, text: "Would you break a promise for $1,000?" },
    { id: 12, text: "Have you ever laughed at someone's misfortune?" },
    { id: 13, text: "Do you believe everyone lies sometimes?" },
    { id: 14, text: "Have you ever faked being busy to avoid someone?" },
    { id: 15, text: "Would you testify against a friend for immunity?" },
    { id: 16, text: "Have you ever kept found money instead of returning it?" },
    { id: 17, text: "Do you exaggerate your accomplishments?" },
    { id: 18, text: "Have you ever lied about your age?" },
    { id: 19, text: "Would you tell a white lie to avoid hurting feelings?" },
    { id: 20, text: "Have you ever pretended not to see someone you know?" },
  ],
};